postgresql:
  enabled: true
  fullnameOverride: db
  auth:
    postgresPassword: openqa
    database: openqa
    username: openqa
    password: openqa

# These values can be set to override the defaults
# worker:
# webui:
