pull_request_rules:
  - name: automatic merge
    conditions:
      - and: &base_checks
        - base=master
        - -label~=^acceptance-tests-needed|not-ready
        # wait explicitly for one of the final checks to show up to be on the
        # safe side even in case of checks not reporting back at all
        - "status-success=codecov/project"
        - "status-success=codecov/patch"
        # wait for OBS package build as well which is triggered independantly
        # See https://progress.opensuse.org/issues/55346 for details
        - "status-success=OBS Package Build"
        - "status-success=static-check-containers"
        - "status-success=webui-docker-compose"
        - "#check-failure=0"
        - "#check-pending=0"
        - linear-history
      - and:
        - "#approved-reviews-by>=2"
        - "#changes-requested-reviews-by=0"
        # https://doc.mergify.io/examples.html#require-all-requested-reviews-to-be-approved
        - "#review-requested=0"
    actions: &merge
      merge:
        method: merge
  - name: automatic merge on special label
    conditions:
      - and: *base_checks
      - and:
        # mergify config checks needs at least two rules in "and" so we repeat
        # one from the base checks
        - base=master
        - "label=merge-fast"
    actions: *merge
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflicts. Could you fix it? 🙏
