# Default values for webui.
# This is a YAML-formatted file.

image:
  name: registry.opensuse.org/devel/openqa/containers15.6/openqa_webui
  pullPolicy: Always
  tag: "latest"

useHttps: false
baseUrl: openqa.host

postgresql:
  enabled: true
  fullnameOverride: db
  auth:
    postgresPassword: openqa
    database: openqa
    username: openqa
    password: openqa
