---
name: 'Perl static checks'

on: [push, pull_request]

jobs:
  perl-lint-checks:
    runs-on: ubuntu-latest
    name: "Perltidy"
    container:
      image: registry.opensuse.org/devel/openqa/containers/os-autoinst_dev
    steps:
      - uses: actions/checkout@v4
      - run: GITHUB_ACTIONS=1 make test-tidy
