---
name: 'Perl author tests'

on: [push, pull_request]

jobs:
  perl-author-tests:
    runs-on: ubuntu-latest
    name: Perl author tests
    container:
      image: registry.opensuse.org/devel/openqa/containers/os-autoinst_dev
    steps:
      - uses: actions/checkout@v4
      - run: make test-author
