debian/tmp/etc/openqa/workers.ini
etc/apparmor.d/usr.share.openqa.script.worker
etc/apparmor.d/local/usr.share.openqa.script.worker
etc/openqa/workers.ini
usr/lib/systemd/system-generators/systemd-openqa-generator /lib/systemd/system-generators/
usr/lib/systemd/system/openqa-worker.target /lib/systemd/system/
usr/lib/systemd/system/openqa-worker@.service /lib/systemd/system/
usr/lib/systemd/system/openqa-worker-auto-restart@.service /lib/systemd/system/
usr/lib/systemd/system/openqa-worker-cacheservice-minion.service /lib/systemd/system/
usr/lib/systemd/system/openqa-worker-cacheservice.service /lib/systemd/system/
usr/lib/systemd/system/openqa-worker-no-cleanup@.service /lib/systemd/system/
usr/lib/systemd/system/openqa-slirpvde.service /lib/systemd/system/
usr/lib/systemd/system/openqa-vde_switch.service /lib/systemd/system/
debian/tmp/usr/lib/sysusers.d/openQA-worker.conf /lib/sysusers.d/
usr/lib/tmpfiles.d/openqa.conf /lib/tmpfiles.d/
usr/share/openqa/lib/OpenQA/CacheService
usr/share/openqa/lib/OpenQA/Worker
usr/share/openqa/script/openqa-slirpvde
usr/share/openqa/script/openqa-vde_switch
usr/share/openqa/script/worker
usr/share/openqa/script/openqa-workercache
usr/share/openqa/script/openqa-workercache-daemon
usr/share/openqa/script/openqa-worker-cacheservice-minion
