etc/openqa/client.conf
etc/openqa/workers.ini
# apparmor profile
etc/apparmor.d/usr.share.openqa.script.worker
# init
usr/lib/systemd/system-generators		lib/systemd/system-generators
usr/lib/systemd/system/openqa-worker.target	lib/systemd/system/openqa-worker.target
usr/lib/systemd/system/openqa-worker@.service	lib/systemd/system/openqa-worker@.service
usr/lib/systemd/system/openqa-slirpvde.service	lib/systemd/system/openqa-slirpvde.service
# This is in spec file but not found in files...
#usr/lib/systemd/system/openqa-worker-no-cleanup@.service	lib/systemd/system/openqa-worker-no-cleanup@.service
usr/lib/systemd/system/openqa-vde_switch.service		lib/systemd/system/openqa-vde_switch.service
## not sure...
usr/lib/tmpfiles.d/openqa.conf	etc/openqa.conf
# worker libs
usr/share/openqa/script/worker
