---
name: check-containers
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  static-check-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test our container definitions
        run: make test-check-containers
