---
name: javascript
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    name: Lint JavaScript code (using Node version ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node (version ${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      - name: npm run lint
        run: npm run lint
