---
name: Perl tests
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      stability_test:
        description: 'Set to 1 to fail if any of the RETRY fails'
        default: 0
      target:
        description: 'Makefile target'
        default: fullstack

jobs:
  fullstack:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/ci/containers/base:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bash -x tools/ci/build_cache.sh
      - name: Build os-autoinst
        run: bash -x tools/ci/build_autoinst.sh
      - name: Make project folder user-writable
        run: sudo chown -R $USER $PWD
      - name: Running unit tests
        run: tools/ci/run_unit_tests.sh ${{ github.event.inputs.target }}
        env:
          STABILITY_TEST: ${{ github.event.inputs.stability_test }}
      - name: Merge coverage databases
        run: cover -write cover_db cover_db*
      - name: Generate coverage report
        run: make coverage-report-html
      - uses: actions/upload-artifact@v4
        with:
          name: Upload artifacts
          path: |
            test-results
            cover_db
        if: always()
